### ISSUE TITLE
Create data and backupdir

### ISSUE THREAD

**Issue by amnesiemaniac** [geerlingguy/ansible-role-gitlab#104]
Hey!
You made a good job with this role.

I have changed gitlab_git_data_dir and backup path.
This does not work. Both directories are not set in config.
It would be usefull to check if it is necessary to create both directories.

I added this in tasks/main.yml. Do you have a better idea?

```
- name: Check data dir and create it if necessary
   file:
     path: "{{ gitlab_git_data_dir }}"
     state: directory
  when: gitlab_git_data_dir != ""

- name: Check backup dir and create it if necessary
   file:
     path: "{{ gitlab_backup_path }}"
     state: directory
  when: gitlab_backup_path != ""
```
