### ISSUE TITLE
Package gitlab-ce not availabe (Debian 9 Stretch)

### ISSUE THREAD

**Issue by micrf** [geerlingguy/ansible-role-gitlab#109]
When trying to run tasks
```
- name: Install GitLab repository
  command:  bash /tmp/gitlab_install_repository.sh
  when: (gitlab_file.stat.exists == false)

- name: Define the Gitlab package name.
  set_fact:
    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
  when: gitlab_version != ''
```
follwing task is failing:
```
- name: Install GitLab
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: present
  when: (gitlab_file.stat.exists == false)
```
is falling:
```
fatal: [rs]: FAILED! => {"changed": false, "msg": "No package matching 'gitlab-ce' is available"}
```
but if I call
```
- command: apt install gitlab-ce
```
package is found and installed!
