### ISSUE TITLE
Automate setting root user credentials and skipping GUI setup phase

### ISSUE THREAD

**Issue by TheNotary** [geerlingguy/ansible-role-gitlab#118]
Great work on this project @geerlingguy thanks for sharing it!

So it all seems to work great without trouble shooting, but I'm researching ways to set the root password during the install for 100% automated installs.  It looks like gitlab supports this through setting environment variables during the [sudo -u git -H bundle exec rake gitlab:setup](https://gitlab.com/gitlab-org/gitlab-ee/blob/master/doc/install/installation.md#initialize-database-and-activate-advanced-features) phase of things.  I'm a bit rusty with Ansible and am having trouble pulling this off, though will look through the code and see if I can manage a PR if possible.  If you have any insights on this task, I'd love to hear them :)

**Comment by TheNotary** [comment]
Ok, after a complete rebuild I've found that you can use ansible to set the required env vars to fully automate the install process:

```
- name: VM Specific Playbook
  environment:
    GITLAB_ROOT_PASSWORD: source_me_from_secret_manager
    GITLAB_ROOT_EMAIL: root@excelsiorcarpetone.com
  hosts: "gitlab-vm"
  any_errors_fatal: true
  become: yes
  become_user: root

  roles:
    - role: geerlingguy.gitlab
      gitlab_external_url: "https://gitlab.{{ vm_domain_name }}"
```

So basically this repo is in perfect working order, though there is an inelegancy in that the root user/pass configurations are assigned in a different way than the other configs, ie `gitlab_external_url`.  With a little time, this could potentially be resolved (not 100% sure though).  

Would you like a PR that adds admin email/ password to be defined in a similar way to the rest of the configurations?  If not, feel free to close this PR, and thanks again for sharing this!!!

**Comment by TheNotary** [comment]
Ok, after a complete rebuild I've found that you can use ansible to set the required env vars to fully automate the install process:

```
- name: VM Specific Playbook
  environment:
    GITLAB_ROOT_PASSWORD: source_me_from_secret_manager
    GITLAB_ROOT_EMAIL: "root@{{ vm_domain_name }}"
  hosts: "gitlab-vm"
  any_errors_fatal: true
  become: yes
  become_user: root

  roles:
    - role: geerlingguy.gitlab
      gitlab_external_url: "https://gitlab.{{ vm_domain_name }}"
```

So basically this repo is in perfect working order, though there is an inelegancy in that the root user/pass configurations are assigned in a different way than the other configs, ie `gitlab_external_url`.  With a little time, this could potentially be resolved (not 100% sure though).  

Would you like a PR that adds admin email/ password to be defined in a similar way to the rest of the configurations?  If not, feel free to close this PR, and thanks again for sharing this!!!
