### ISSUE TITLE
fetch gitlab_ssl_certificate so the gitlab-runners can use it

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-role-gitlab#127]
One task that runs is `Create self-signed certificate.` 

This task creates `{{ gitlab_ssl_certificate }}`, self-signed. If I want to register a gitlab-runner on other machines, then I need to `copy:` it to these gitlab-runner machines. Having it available in `files/` would be really convenient.

**Comment by bbaassssiiee** [comment]
```yaml
- name: fetch certificate
  fetch:
    src: /etc/gitlab/ssl/gitlab.crt
    dest: files/certs/{{ gitlab_host }}.crt
    flat: true
```
