### ISSUE TITLE
Boolean values in gitlab_extra_settings are capitalized in gitlab.rb

### ISSUE THREAD

**Issue by Normo** [geerlingguy/ansible-role-gitlab#154]
When adding a boolean value to `gitlab_extra_settings` it will be added capitalized to `gitlab.rb`, but boolean values in ruby have to be lower-case.
This results in an `uninitialized constant #<Class:Gitlab>::False` or `uninitialized constant #<Class:Gitlab>::True` error when running ` gitlab-ctl reconfigure`.

For example:
```yaml
gitlab_extra_settings:
  - postgresql:
      - key: "enable"
        value: false
```
results in:
```rb
# Extra configuration
postgresql['enable'] = False
```

**Comment by olo-dw** [comment]
@Normo : did you try with a `type: "plain"` ?

```
gitlab_extra_settings:
  - postgresql:
      - key: "enable"
        value: "false"
        type: "plain"
```
