### ISSUE TITLE
registry let's encrypt ssl certificate not valid with default config

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [geerlingguy/ansible-role-gitlab#156]
Hello,

Maybe a good idea to give an example how to use a Let's encrypt certificate on your registry url.
Default config allow us to use our own certificate on a specific path:

```
# GitLab registry.
registry['enable'] = {{ gitlab_registry_enable }}
{% if gitlab_registry_enable %}
registry_external_url "{{ gitlab_registry_external_url }}"
registry_nginx['ssl_certificate'] = "{{ gitlab_registry_nginx_ssl_certificate }}"
registry_nginx['ssl_certificate_key'] = "{{ gitlab_registry_nginx_ssl_certificate_key }}"
{% endif %}
```

With the default values of the role:
```
gitlab_registry_enable: "true"
gitlab_registry_external_url: "https://gitlab.example.com:4567"
gitlab_registry_nginx_ssl_certificate: "/etc/gitlab/ssl/gitlab.crt"
gitlab_registry_nginx_ssl_certificate_key: "/etc/gitlab/ssl/gitlab.key"
```
When adding letsencrypt in the gitlab_extra_settings section, you need to overwrite the gitlab_registry_nginx_ssl_certificate and gitlab_registry_nginx_ssl_certificate_key with empty strings.

```
gitlab_extra_settings:
  - letsencrypt:
      - key: "enable"
        value: "true"
      - key: "contact_emails"
        value: ['test@test.com']
      - key: "auto_renew"
        value: "true"

gitlab_registry_nginx_ssl_certificate: ""
gitlab_registry_nginx_ssl_certificate_key: ""
```
