### ISSUE TITLE
properly way to run role

### ISSUE THREAD

**Issue by Nurlan199206** [geerlingguy/ansible-role-gitlab#210]
Hi

How to run role properly? i cannot even install it.

```
main.yml

- hosts: servers
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.gitlab }

```

```
ansible-playbook -kb main.yml -i inventory/hosts.yml
SSH password:
ERROR! the role 'geerlingguy.gitlab' was not found in /home/nurlan/ansible-role-gitlab-master/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/nurlan/ansible-role-gitlab-master

The error appears to be in '/home/nurlan/ansible-role-gitlab-master/main.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - { role: geerlingguy.gitlab }
      ^ here

```
