### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by marselsultanov** [geerlingguy/ansible-role-gitlab#212]
Hello, can you please explain, how password will be a 5iveL!fe instead of randomly generated like in this instruction:
https://docs.gitlab.com/omnibus/installation/index.html#set-up-the-initial-password
?

**Comment by NormanJS** [comment]
Last time I tried, it was randomly generated. Though, you can manually set the password and email by setting the environment variables `GITLAB_ROOT_EMAIL` or `GITLAB_ROOT_PASSWORD`, you can set these within a playbook like this:
```
- name: Gitlab
  environment:
     GITLAB_ROOT_PASSWORD: "{{ gitlab_password }}"
     GITLAB_ROOT_EMAIL: "{{ gitlab_email }}"
 ```
