### ISSUE TITLE
Internal Gitlab registry failing auth with 401

### ISSUE THREAD

**Issue by BrutalBirdie** [geerlingguy/ansible-role-gitlab#215]
Tracking Issue for PR.
In the defaults `gitlab_external_url` is mentioned with a trailing `/` this will result in a bad registry configuration:

path: `/var/opt/gitlab/registry/config.yml`
```yaml
auth:
  token:
    realm: https://sub.domain.tld//jwt/auth
```
because in the `gitlab.rb` file the `external_url "https://sub.domain.tld/"` will be combined with the `/jwt/auth` leading to `//` in the domain. (Sorry could not find the internal gitlab code where this happens)
